# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4afeccab9102ee6371dec36d7abd8a270a0d8d94ff0d41679d9ec277cc4bf78cf6a3b35a199d3295694ff49e67a92de52dd5a6a1510346bb0bf98ae6ae2e87e

test:
  secret_key_base: 5382471e760ac1ef9fdb1848f9811f5d62b06c938a65f9e829a5ba1f872e58448f7aa6908f6c5376de48fff425d43a1c77b8e67fee9b0bd9a7ecbf337bbd5734

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
